// Рендер: releases/<id>/source.html → 01.png…NN.png (1080×1350), contact-sheet.png, index.html. Headless Chromium через Playwright.
import {existsSync,readFileSync,readdirSync,writeFileSync} from "node:fs";
import {dirname,isAbsolute,join,resolve} from "node:path";
import {fileURLToPath,pathToFileURL} from "node:url";
const repo=resolve(dirname(fileURLToPath(import.meta.url)),"..");if(!process.argv[2]){console.error("usage: node scripts/render.mjs releases/<id>");process.exit(1)}const out=resolve(process.argv[2]);
const meta=JSON.parse(readFileSync(join(out,"meta.json"),"utf8"));const ids=meta.slides.map(s=>s.id),labels=meta.slides.map(s=>s.label);
async function chromiumApi(){for(const c of ["playwright"]){try{const m=await import(isAbsolute(c)?pathToFileURL(c).href:c);if(m.chromium)return m.chromium;if(m.default?.chromium)return m.default.chromium}catch{}}throw new Error("Playwright unavailable")}
function chromiumPath(){const root=join(process.env.HOME||"","Library/Caches/ms-playwright");if(!existsSync(root))return null;for(const b of readdirSync(root).filter(n=>/^chromium-\d+$/.test(n)).sort().reverse())for(const rel of ["chrome-mac-arm64/Chromium.app/Contents/MacOS/Chromium","chrome-mac/Chromium.app/Contents/MacOS/Chromium"]){const p=join(root,b,rel);if(existsSync(p))return p}return null}
const t0=Date.now();
const chromium=await chromiumApi(),executablePath=chromiumPath();const browser=await chromium.launch({headless:true,...(executablePath?{executablePath}:{}),args:["--force-color-profile=srgb","--hide-scrollbars"]});
const page=await browser.newPage({viewport:{width:1100,height:1370},deviceScaleFactor:1});await page.goto(pathToFileURL(join(out,"source.html")).href,{waitUntil:"networkidle"});await page.evaluate(()=>document.fonts.ready);
const overflow=await page.evaluate(()=>[...document.querySelectorAll(".slide *")].filter(el=>{const s=el.closest(".slide").getBoundingClientRect(),r=el.getBoundingClientRect();return r.width>0&&(r.right>s.right+1||r.bottom>s.bottom+1||el.scrollWidth>el.clientWidth+2&&getComputedStyle(el).overflow==="visible"&&el.children.length===0)}).map(el=>el.closest(".slide").id+" "+el.className+" "+(el.textContent||"").slice(0,40)));
for(const id of ids)await page.locator("#slide-"+id).screenshot({path:join(out,id+".png")});
const cards=ids.map((id,i)=>`<article><img src="${id}.png"><b>${id} · ${labels[i]}</b></article>`).join("");
writeFileSync(join(out,"contact-sheet.html"),`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;background:#151515;color:#f5ead7;font-family:system-ui}.board{width:2030px;padding:48px;display:grid;grid-template-columns:repeat(4,470px);gap:28px 18px}.title{grid-column:1/-1;font-size:38px;font-weight:800}article img{width:440px;height:550px;object-fit:cover;border-radius:14px;box-shadow:0 16px 36px #0008}article b{display:block;margin-top:9px;font-size:17px}</style></head><body><main class="board"><div class="title">${meta.title} · ${ids.length} слайдов</div>${cards}</main></body></html>`);
writeFileSync(join(out,"index.html"),`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>${meta.title}</title><style>body{margin:0;background:#171717;color:#f6ead8;font:16px system-ui;padding:32px}h1{margin:0 0 8px}.hint{opacity:.6;margin-bottom:22px}.rail{display:flex;gap:22px;overflow:auto;scroll-snap-type:x mandatory}.rail img{width:432px;height:540px;object-fit:cover;border-radius:17px;scroll-snap-align:start;box-shadow:0 18px 50px #0008}</style></head><body><h1>${meta.title}</h1><div class="hint">Листайте по горизонтали · ${ids.length} слайдов</div><div class="rail">${ids.map(id=>`<img src="${id}.png">`).join("")}</div></body></html>`);
const board=await browser.newPage({viewport:{width:2126,height:1360},deviceScaleFactor:1});await board.goto(pathToFileURL(join(out,"contact-sheet.html")).href,{waitUntil:"networkidle"});await board.screenshot({path:join(out,"contact-sheet.png"),fullPage:true});await board.close();await browser.close();
console.log(`Rendered ${ids.length} slides in ${((Date.now()-t0)/1000).toFixed(1)} s`);if(overflow.length)console.log("OVERFLOW (проверь визуально, рендер обложки выходит за край намеренно):\n"+overflow.join("\n"));
